version: 1.0.0

services:
  api:
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - '8090:80'
    volumes:
      - .:/app
    environment:
      PROJECT_SERVICE_TYPE: 'api'
    depends_on:
      - db
    links:
      - db:database
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  redis:
    image: redis:latest
    ports:
      - 6379
  worker:
    build: .
    entrypoint: ./entrypoint.sh
    environment:
      PROJECT_SERVICE_TYPE: 'worker'
    depends_on:
      - redis
      - db
      - api
    volumes:
      - .:/app

