FROM public.ecr.aws/lambda/python:3.10 AS base
WORKDIR /app
COPY . /app
RUN pip install -U pip
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN ~/.local/share/pypoetry/venv/bin/poetry update
RUN ~/.local/share/pypoetry/venv/bin/poetry export --dev -f requirements.txt > requirements.txt
RUN pip install -r requirements.txt
