"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
import sys
from pathlib import Path

import stringcase
from asbool import asbool
from loguru import logger
from stela import settings

from core import __version__
from core.tools.debug import show_toolbar

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_NAME = stringcase.titlecase(settings["project.name"])


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/
ENV = settings["ENV"]
RUNNING_TESTS = "pytest" in sys.modules or "test" in sys.argv
SERVICE_TYPE = settings["project.service_type"]
SHOW_DJANGO_PAGES = settings["project.show_django_pages"]
AUTH_API_URL = settings["project.auth_api_url"]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings["project.secret_key"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = asbool(settings["project.debug"])

ALLOWED_HOSTS = settings["project.allowed_hosts"]

LOGIN_URL = "/admin/login"

TOOLBAR_ALLOWED_HOSTS = [
    "localhost:8000",
    "localhost:8247",
    "127:0.0.1:8247",
]

DEBUG_TOOLBAR_CONFIG = {"SHOW_TOOLBAR_CALLBACK": show_toolbar, "SHOW_COLLAPSED": True}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_THROTTLE_RATES": {"anon": "6/minute"},
}

if DEBUG:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"].append("rest_framework.renderers.BrowsableAPIRenderer")

SWAGGER_DESCRIPTION = """
### Welcome to Back-Edesoft API
#### Environment is: {env}

Please check the following links to understand *OpenAPI* specifications:
* [OpenAPI Specification](https://swagger.io/specification/)
* [DRF Spectacular](https://github.com/tfranzel/drf-spectacular)
"""


SPECTACULAR_SETTINGS = {
    "TITLE": "Back-Edesoft API",
    "DESCRIPTION": SWAGGER_DESCRIPTION.format(env=ENV.upper()),
    "VERSION": __version__,
    "SERVE_INCLUDE_SCHEMA": True,
}

# Application definition

INSTALLED_APPS = [
    "django_celery_results",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    "drf_spectacular",
    "rest_framework",
    "corsheaders",
    "back_edesoft",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

if RUNNING_TESTS:
    logger.debug("Starting Internal Database for Unit Tests...")
else:
    logger.info(f"Configuring Database {settings['db.name']} {settings['db.host']}...")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": settings["db.name"],
        "USER": settings["db.user"],
        "PASSWORD": settings["db.password"],
        "HOST": settings["db.host"],
        "PORT": settings["db.port"],
        "OPTIONS": {"options": f"-c search_path={settings['project.database_schemas']}"},
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# CORS
CORS_ALLOW_ALL_ORIGINS = asbool(settings["project.allow_all_origins"])
CORS_ALLOW_HEADERS = ("content-type", "authorization", "accept", "origin", "user-agent")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Project Settings
SECRET_TOKEN = settings["project.secret_key"]

# Celery Settings
CELERY_BROKER_URL = "redis://redis:6379"
CELERY_RESULT_BACKEND = "redis://redis:6379"
TASK_SERIALIZER = "json"
RESULT_SERIALIZER = "json"
ACCEPT_CONTENT = ["json"]
ENABLE_UTC = True
