# Generated by Django 4.1.7 on 2023-03-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=25)),
                ("cpf", models.CharField(max_length=14)),
                ("phone", models.CharField(max_length=15)),
                ("cnpj", models.CharField(max_length=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
